name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: false
      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.4
      - name: install packages
        run: bun install
      - name: Build
        run: bun run build-prod
      - uses: actions/upload-artifact@v4
        with:
          path: out/index.html
          retention-days: 1
